[build]
  base = "myblog"
  publish = "myblog/build"
  functions = "my-blog-backend/src"
  command = "yarn run build"

[functions]
  external_node_modules = ["mongodb"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
